version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: datanaut
      POSTGRES_PASSWORD: datanaut
      POSTGRES_DB: datanaut
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
