/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { AppTable } from "./appTable";

export interface AppColumn {
  id?: string;
  tableId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  config?: string | null;
  position?: number;
  isRequired?: boolean;
  /** @nullable */
  options?: string | null;
  createdAt?: string;
  updatedAt?: string;
  table?: AppTable;
}
