/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { AppColumn } from "./appColumn";
import type { AppRow } from "./appRow";

export interface AppCell {
  id?: string;
  rowId?: string;
  columnId?: string;
  /** @nullable */
  value?: string | null;
  createdAt?: string;
  updatedAt?: string;
  column?: AppColumn;
  row?: AppRow;
}
