/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { AppCell } from "./appCell";
import type { AppTable } from "./appTable";

export interface AppRow {
  id?: string;
  tableId?: string;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  position?: number | null;
  /** @nullable */
  appCells?: AppCell[] | null;
  table?: AppTable;
}
