/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Datanaut API
 * Datanaut is a cloud-based platform that combines the functionality of a spreadsheet with a database, allowing users to organize, collaborate on, and customize data in a visually intuitive interface
 * OpenAPI spec version: 1.0.0
 */
import type { AppRowData } from "./appRowData";

export interface AppRow {
  /** The row ID */
  id: string;
  /** The table this row belongs to */
  table_id: string;
  /** The row data as key-value pairs */
  data: AppRowData;
  /** User ID who created this row */
  created_by: string;
  created_at: string;
  updated_at: string;
}
