/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */

export interface ColumnDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: string | null;
  tableId?: string;
  createdAt?: string;
  updatedAt?: string;
}
