/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { CreateColumnDto } from "./createColumnDto";

export interface CreateTableDto {
  /** @nullable */
  name?: string | null;
  workspaceId?: string;
  /** @nullable */
  columns?: CreateColumnDto[] | null;
}
