/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */

export interface CreateColumnRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: string | null;
  tableId?: string;
  position?: number;
  isRequired?: boolean;
  /** @nullable */
  config?: string | null;
  /** @nullable */
  options?: string | null;
}
