/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";

export interface RefreshToken {
  id?: string;
  userId?: string;
  /** @nullable */
  token?: string | null;
  expiresAt?: string;
  revoked?: boolean;
  createdAt?: string;
  /** @nullable */
  revokedAt?: string | null;
  /** @nullable */
  replacedByToken?: string | null;
  /** @nullable */
  reasonRevoked?: string | null;
  user?: User;
}
