/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { WorkspaceDto } from "./workspaceDto";
import type { ColumnDto } from "./columnDto";
import type { RowDto } from "./rowDto";

export interface TableDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  workspace?: WorkspaceDto;
  /** @nullable */
  columns?: ColumnDto[] | null;
  /** @nullable */
  rows?: RowDto[] | null;
  createdAt?: string;
  updatedAt?: string;
}
