/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { ColumnDto } from "./columnDto";

export interface TableDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  workspaceId?: string;
  /** @nullable */
  columns?: ColumnDto[] | null;
  createdAt?: string;
  updatedAt?: string;
}
