/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";
import type { Workspace } from "./workspace";

export interface Tenant {
  id?: string;
  /** @nullable */
  name?: string | null;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  users?: User[] | null;
  /** @nullable */
  workspaces?: Workspace[] | null;
}
