/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Datanaut API
 * Datanaut is a cloud-based platform that combines the functionality of a spreadsheet with a database, allowing users to organize, collaborate on, and customize data in a visually intuitive interface
 * OpenAPI spec version: 1.0.0
 */

export interface Tenant {
  /** The tenant ID */
  id: string;
  /** The tenant name */
  name: string;
  created_at: string;
  updated_at: string;
}
