/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */

export interface UpdateColumnDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: string | null;
}
