/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateCellDtoValue } from "./updateCellDtoValue";

export interface UpdateCellDto {
  /** @nullable */
  value?: UpdateCellDtoValue;
}
