/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */

export interface UpdateRowCellDto {
  id?: string;
  /** @nullable */
  value?: string | null;
}
