/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateRowCellDto } from "./updateRowCellDto";

export interface UpdateRowDto {
  /** @nullable */
  cells?: UpdateRowCellDto[] | null;
}
