/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { RefreshToken } from "./refreshToken";
import type { Role } from "./role";
import type { Tenant } from "./tenant";

export interface User {
  id?: string;
  tenantId?: string;
  roleId?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  name?: string | null;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  refreshTokens?: RefreshToken[] | null;
  role?: Role;
  tenant?: Tenant;
}
