/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Datanaut API
 * Datanaut is a cloud-based platform that combines the functionality of a spreadsheet with a database, allowing users to organize, collaborate on, and customize data in a visually intuitive interface
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  /** The user ID */
  id: string;
  /** The tenant this user belongs to */
  tenant_id: string;
  /** The user's email */
  email: string;
  /** The user's name */
  name: string;
  /** Hashed password */
  password_hash: string;
  created_at: string;
  updated_at: string;
}
