/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { AppTable } from "./appTable";
import type { Tenant } from "./tenant";

export interface Workspace {
  id?: string;
  /** @nullable */
  name?: string | null;
  createdAt?: string;
  updatedAt?: string;
  tenantId?: string;
  /** @nullable */
  appTables?: AppTable[] | null;
  tenant?: Tenant;
}
