/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import type { TenantDto } from "./tenantDto";
import type { TableDto } from "./tableDto";

export interface WorkspaceDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  tenant?: TenantDto;
  /** @nullable */
  tables?: TableDto[] | null;
  createdAt?: string;
  updatedAt?: string;
}
