/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  AuthResponse,
  LoginRequest,
  LoginResponse,
  VerifyRequest,
} from ".././model";

import { customFetch } from "../../../utilities/api";
import { useCustomMutatorOptions } from "../../../features/api/hooks/useCustomMutatorOptions";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type postAuthLoginResponse200 = {
  data: LoginResponse;
  status: 200;
};

export type postAuthLoginResponseComposite = postAuthLoginResponse200;

export type postAuthLoginResponse = postAuthLoginResponseComposite & {
  headers: Headers;
};

export const getPostAuthLoginUrl = () => {
  return `/api/auth/login`;
};

export const postAuthLogin = async (
  loginRequest: LoginRequest,
  options?: RequestInit,
): Promise<postAuthLoginResponse> => {
  return customFetch<postAuthLoginResponse>(getPostAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginRequest),
  });
};

export const usePostAuthLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationKey = ["postAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data: LoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data, requestOptions);
  };

  const customOptions = useCustomMutatorOptions(
    { ...mutationOptions, mutationFn },
    { url: `/api/auth/login` },
    { operationId: "PostAuthLogin", operationName: "postAuthLogin" },
  );

  return customOptions;
};

export type PostAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;
export type PostAuthLoginMutationBody = LoginRequest;
export type PostAuthLoginMutationError = unknown;

export const usePostAuthLogin = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationOptions = usePostAuthLoginMutationOptions(options);

  return useMutation(mutationOptions);
};
export type postAuthVerifyResponse200 = {
  data: AuthResponse;
  status: 200;
};

export type postAuthVerifyResponseComposite = postAuthVerifyResponse200;

export type postAuthVerifyResponse = postAuthVerifyResponseComposite & {
  headers: Headers;
};

export const getPostAuthVerifyUrl = () => {
  return `/api/auth/verify`;
};

export const postAuthVerify = async (
  verifyRequest: VerifyRequest,
  options?: RequestInit,
): Promise<postAuthVerifyResponse> => {
  return customFetch<postAuthVerifyResponse>(getPostAuthVerifyUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(verifyRequest),
  });
};

export const usePostAuthVerifyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthVerify>>,
    TError,
    { data: VerifyRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthVerify>>,
  TError,
  { data: VerifyRequest },
  TContext
> => {
  const mutationKey = ["postAuthVerify"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthVerify>>,
    { data: VerifyRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthVerify(data, requestOptions);
  };

  const customOptions = useCustomMutatorOptions(
    { ...mutationOptions, mutationFn },
    { url: `/api/auth/verify` },
    { operationId: "PostAuthVerify", operationName: "postAuthVerify" },
  );

  return customOptions;
};

export type PostAuthVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthVerify>>
>;
export type PostAuthVerifyMutationBody = VerifyRequest;
export type PostAuthVerifyMutationError = unknown;

export const usePostAuthVerify = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthVerify>>,
    TError,
    { data: VerifyRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthVerify>>,
  TError,
  { data: VerifyRequest },
  TContext
> => {
  const mutationOptions = usePostAuthVerifyMutationOptions(options);

  return useMutation(mutationOptions);
};
export type postAuthRefreshResponse200 = {
  data: void;
  status: 200;
};

export type postAuthRefreshResponseComposite = postAuthRefreshResponse200;

export type postAuthRefreshResponse = postAuthRefreshResponseComposite & {
  headers: Headers;
};

export const getPostAuthRefreshUrl = () => {
  return `/api/auth/refresh`;
};

export const postAuthRefresh = async (
  options?: RequestInit,
): Promise<postAuthRefreshResponse> => {
  return customFetch<postAuthRefreshResponse>(getPostAuthRefreshUrl(), {
    ...options,
    method: "POST",
  });
};

export const usePostAuthRefreshMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postAuthRefresh"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    void
  > = () => {
    return postAuthRefresh(requestOptions);
  };

  const customOptions = useCustomMutatorOptions(
    { ...mutationOptions, mutationFn },
    { url: `/api/auth/refresh` },
    { operationId: "PostAuthRefresh", operationName: "postAuthRefresh" },
  );

  return customOptions;
};

export type PostAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRefresh>>
>;

export type PostAuthRefreshMutationError = unknown;

export const usePostAuthRefresh = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = usePostAuthRefreshMutationOptions(options);

  return useMutation(mutationOptions);
};
export type postAuthLogoutResponse200 = {
  data: void;
  status: 200;
};

export type postAuthLogoutResponseComposite = postAuthLogoutResponse200;

export type postAuthLogoutResponse = postAuthLogoutResponseComposite & {
  headers: Headers;
};

export const getPostAuthLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const postAuthLogout = async (
  options?: RequestInit,
): Promise<postAuthLogoutResponse> => {
  return customFetch<postAuthLogoutResponse>(getPostAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const usePostAuthLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postAuthLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogout>>,
    void
  > = () => {
    return postAuthLogout(requestOptions);
  };

  const customOptions = useCustomMutatorOptions(
    { ...mutationOptions, mutationFn },
    { url: `/api/auth/logout` },
    { operationId: "PostAuthLogout", operationName: "postAuthLogout" },
  );

  return customOptions;
};

export type PostAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogout>>
>;

export type PostAuthLogoutMutationError = unknown;

export const usePostAuthLogout = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = usePostAuthLogoutMutationOptions(options);

  return useMutation(mutationOptions);
};
